# project yaml file for github actions training

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.gitignore'
      - '*.md'
      - "**/**.md"
      - 'LICENSE.txt'

  pull_request:
    branches:
      - main

  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true
#  group: ${{ github.workflow }}-${{ github.ref }}
#  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write


jobs:
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4
      # Setup Node (version 18+)
      - uses: actions/setup-node@v4
        with:
            node-version: v24.16.0
      # Install all the dependencies needed. Use the cache to speed up the process
      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - run: npm install
      # Run all the linters
#      - run: npm run lint
      # Run all the scripts in the folder script/**
      - run: node ./script/url-checker.js


  build:
    needs: test
    runs-on: ubuntu-latest
    env:
      PATH_PREFIX: /cd13461-github-actions-project-starter/
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4
      # Setup Node (version 18+) --> deprecated, so ignore
      - uses: actions/setup-node@v4
        with:
            node-version: v24.16.0

      # Install all the dependencies needed. Use the cache to speed up the process
      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
                    ${{ runner.os }}-npm-
      - run: npm install
      - name: Build site
        run: |
          mkdir _site
          echo "<h1>🐛My site finally set up!🦋</h1>" > _site/index.html
      # Setup pages
      - uses: actions/configure-pages@v4
      # Use GitHub Actions artifacts to upload a zip file
      - uses: actions/upload-pages-artifact@v3

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: _site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4






