# project yaml file for github actions training

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.gitignore'
      - '*.md'
      - "**/**.md"
      - 'LICENSE.txt'

  pull_request:
    branches:
      - main

  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false
#  group: ${{ github.workflow }}-${{ github.ref }}
#  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write


jobs:
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4
      # Setup Node (version 18+)
      - uses: actions/setup-node@v4
      # Install all the dependencies needed. Use the cache to speed up the process
      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - run: npm install
      # Run all the linters
#      - run: npm run lint
      # Run all the scripts in the folder script/**
      - run: node ./script/url-checker.js







#  build:
#
#
#
#  deploy:




